### ISSUE TITLE
Funny examples

### ISSUE THREAD

**Issue by wintercounter** [fahad19/proppy#13]
Funny how "without" examples are written using the longest possible syntax while "with" examples utilizing the shortest syntax to make it look cleaner when it's not.

**Comment by fahad19** [comment]
Thanks for taking the time to go through the examples! 💖 

Raw examples are written in a way so that those who already know React/Vue/Rx/Redux can understand what we are trying to show as an example first.

Then comes the ProppyJS examples which are just function calls. That's why they are written that way.

The lines of code are insignificant here. It's the expressiveness of the code that's important in the examples :)

**Comment by wintercounter** [comment]
Even eslint would throw warning to this.

```
    if (nextProps.counter % 2 !== 0) {
      return false;
    }
    return true;
```
